language: python

dist: bionic

env:
  global:
    - SDSS_LOCAL_SAS_MIRROR=/home/travis/build/henrysky
    - GAIA_TOOLS_DATA=/home/travis/build/henrysky
    - LASMOT_DR5_DATA=/home/travis/build/henrysky

matrix:
  include:
    - env: LATEST_FLAG=true TF_VER="tensorflow-cpu==2.3.0" TFP_VER="0.11.0" PAPER_MODELS=false  # beta, allow failure
    - env: LATEST_FLAG=true TF_VER="tensorflow-cpu==2.3.0" TFP_VER="0.11.0" PAPER_MODELS=true   # beta, allow failure
    - env: LATEST_FLAG=true TF_VER="tensorflow-cpu==2.2.0" TFP_VER="0.10.1" PAPER_MODELS=false  # latest 2.x version config
    - env: LATEST_FLAG=true TF_VER="tensorflow-cpu==2.2.0" TFP_VER="0.10.1" PAPER_MODELS=true   # latest 2.x version config for model testing
#  allow_failures:
#    - env: LATEST_FLAG=true TF_VER="tensorflow-cpu==2.3.0-rc2" TFP_VER="0.11.0-rc0" PAPER_MODELS=false  # beta, allow failure
#    - env: LATEST_FLAG=true TF_VER="tensorflow-cpu==2.3.0-rc2" TFP_VER="0.11.0-rc0" PAPER_MODELS=true   # beta, allow failure

python:
  - "3.7"

services:
  - xvfb  # configure a headless display to test plot generation

addons:
  apt:
    packages:
     - graphviz  # For model plotting

install:
  - pip install coverage
  - pip install coveralls
  - pip install $TF_VER  # because tensorflow is not in compulsory requirement
  - pip install tensorflow-probability==$TFP_VER  # because tfp is not in compulsory requirement
  - pip install pydot
  - pip install graphviz
  - python setup.py install
  - python -c "from astroNN.config import tf_patch; tf_patch()"  # patching tensorflow if needed

script:
  - |
    if [ $LATEST_FLAG == true ] && [ $PAPER_MODELS == false ]; then coverage run --source=astroNN -m unittest \
    tests.test_numpy_tools tests.test_loss_func tests.test_layers \
    tests.test_apogee_tools tests.test_datasets tests.test_gaia_tools tests.test_lamost_tools  \
    tests.test_models tests.test_utilities tests.test_neuralODE; fi  # Run almost all tests for latest config
  - if [ $PAPER_MODELS == true ]; then coverage run --source=astroNN -m unittest tests.test_apogee_model tests.test_paper_models; fi  # Run papers models test
  - |
    if [ $LATEST_FLAG == false ]; then coverage run --source=astroNN -m unittest \
    tests.test_layers tests.test_loss_func tests.test_models tests.test_neuralODE; fi  # Run partial tests for non latest config

after_success:
  - coveralls # To upload reports to coveralls.io

notifications:
  slack:
      on_success: change